project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 1_introduction.qmd
        text: Introduction
      - href: 2_curation.qmd
        text: Curation
      - href: 3.Analysis.qmd
        text: Analysis
      - href: 4.Results.qmd
        text: Results
      - href: 5.Extension.qmd
        text: Extension
    right:
      - icon: github
        href: https://github.com/ImperialCollegeLondon/The-Random-Side-A-Mixed-Model-Adventure/tree/main  # include your GitHub repo URL
        aria-label: GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    